language: "node_js"
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
  - "iojs"

before_install:
 - "bash support/bin/travis-install.sh"

script: "make ci-travis"

after_success:
  - "make submit-cov-to-coveralls"
